# Python para Engenharia de Dados
----

### Estrutura de dados

* LISTA - list
* TUPLA  - tuple
* DICIONÁRIO - dict
* CONJUNTO - set

### Lista - list

* Sequência de objetos, separados por vírgula, armazenados dentro de colchetes ( [ ] )
* Uma lista vazia é representada por [ ]<br><p>
Exemplo:<br>
lista = []<br>
lista2 = [1, 2, 'Introdução a Python', [1,3,4]]

In [33]:
lista = []
lista2 = [1, 2, 'Introdução a Python', [1,3,4]]
print(type(lista)) #<class 'list’>

<class 'list'>


In [35]:
# Os elementos de uma lista são acessados através de seu índice (iniciando em 0)
print(lista2[0]) #1
print(lista2[3]) #[1,3,4]
print(lista2[3][1]) #??

1
[1, 3, 4]
3


In [36]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista3 = lista1 + lista2
print('Concatenação de duas listas:', lista3)

Concatenação de duas listas: [1, 2, 3, 4, 5, 6]


In [37]:
lista4 = lista1 * 3
print('Repetição de elementos de uma lista: ', lista4)

Repetição de elementos de uma lista:  [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [38]:
ista = [1, 2, 3, 10, 25]
print('Verificando elementos na lista: ')
print(34 in lista)
print(10 in lista)

Verificando elementos na lista: 
False
False


In [39]:
# Cria uma lista com vários tipos de dados
lista1 = [100, 3, 'Introdução a Python', [10,20,30]]

# Imprime uma mensagem de texto
print('Percorrendo a lista...')

# Loop for para percorrer cada elemento da lista
for l in lista1:
    # Imprime cada elemento da lista
    print(l)


Percorrendo a lista...
100
3
Introdução a Python
[10, 20, 30]


In [41]:
# Cria uma lista com vários tipos de dados
lista = [100, 3, 'Introdução a Python', [10,20,30]]

# Imprime uma mensagem de texto
print('Percorrendo a lista...')

# Loop for para percorrer cada elemento da lista
for l in lista:
    # Verifica se o elemento atual é uma lista
    if (isinstance(l, list)):
        # Loop for para percorrer cada elemento da lista aninhada
        for l2 in l:
            # Imprime cada elemento da lista aninhada
            print(l2)
    else:
        # Imprime o elemento se não for uma lista
        print(l)


Percorrendo a lista...
100
3
Introdução a Python
10
20
30


Esse código cria uma lista chamada lista com vários números inteiros. Em seguida, ele usa a técnica de "fatiamento" para obter uma sublista da posição 1 (segundo elemento) até a posição 4 (quinto elemento, que não é incluído) da lista original e a imprime na saída.

Depois disso, o código usa novamente a técnica de "fatiamento" para obter uma cópia da lista original em ordem inversa, e a imprime na saída.

Aqui está uma explicação linha por linha do código:

In [42]:
# Cria uma lista com vários números inteiros
lista = [1, 2, 3, 10, 25]

# Imprime a mensagem de texto e a sublista da posição 1 à posição 4 da lista original
print('Fatiando a lista: ' + str(lista[1:4]))

# Imprime a mensagem de texto e uma cópia da lista original em ordem inversa
print('Imprimindo a lista em ordem inversa: ' + str(lista[::-1]))


Fatiando a lista: [2, 3, 10]
Imprimindo a lista em ordem inversa: [25, 10, 3, 2, 1]


In [45]:
lista = [190, 87, 3, 82, 4]
print('Maior elemento da lista: ', max(lista))
print('Menor elemento da lista: ', min(lista))
print('Soma dos elementos da lista: ', sum(lista))
print('Quantidade de elementos da lista: ', len(lista))
print('Média dos elementos da lista: ', sum(lista)/len(lista))

Maior elemento da lista:  190
Menor elemento da lista:  3
Soma dos elementos da lista:  366
Quantidade de elementos da lista:  5
Média dos elementos da lista:  73.2


O código abaixo utiliza a biblioteca NumPy para calcular a média da lista através da função np.mean(), que retorna a média aritmética dos elementos da lista.
É importante ressaltar que, para utilizar a biblioteca NumPy, é necessário instalá-la previamente através do gerenciador de pacotes do Python, como o pip.

In [46]:
import numpy as np
print('Média dos elementos da lista utilizando a biblioteca numpy: ', np.mean(lista))

Média dos elementos da lista utilizando a biblioteca numpy:  73.2


In [47]:
lista = []
print('Adicionando itens no final da lista...')
lista.append('Introdução a Python')
lista.append('Redes de Computadores')
print(lista)
print('Adicionando item em uma posição específica...')
lista.insert(1, 'Banco de Dados')
print(lista)

Adicionando itens no final da lista...
['Introdução a Python', 'Redes de Computadores']
Adicionando item em uma posição específica...
['Introdução a Python', 'Banco de Dados', 'Redes de Computadores']


Esses comandos abaixo permitem gerar números aleatórios de diferentes tipos e intervalos. Aqui está uma breve explicação de cada um:

random(): gera um número real aleatório entre 0 e 1.<br>
uniform(a, b): gera um número real aleatório entre a e b (inclusive).<br>
randint(a, b): gera um número inteiro aleatório entre a e b (inclusive).<br>
randrange(a, b, c): gera um número inteiro aleatório entre a e b, com um passo de c. Note que o valor b não está incluído no intervalo.<br>
Por exemplo, randrange(10, 20, 2) irá gerar um número inteiro aleatório par entre 10 e 18 (ou seja, não inclui o valor 20).

In [48]:
from random import *
print ('Gerando número real entre 0 e 1:', random())
print ('Gerando número real entre 10 e 20:', uniform(10,20))
print ('Gerando número inteiro entre 10 e 20:', randint(10,20))
print ('Gerando número par entre 10 e 20:', randrange(10,20,2))

Gerando número real entre 0 e 1: 0.15569516997103128
Gerando número real entre 10 e 20: 17.512690422728884
Gerando número inteiro entre 10 e 20: 19
Gerando número par entre 10 e 20: 10


Uma ótima maneira de gerar uma lista com números aleatórios! O método sample da biblioteca random é usado para escolher uma amostra aleatória única de tamanho k de uma sequência. No exemplo, estamos gerando uma lista com 10 números aleatórios únicos entre 1 e 100. 

In [49]:
from random import sample
lista = sample(range(1, 101), 10)
print('Lista com números aleatórios de 1 a 100:' + str(lista))

Lista com números aleatórios de 1 a 100:[57, 16, 31, 52, 63, 8, 61, 6, 88, 53]


O código abaixo une duas listas, lista1 e lista2, utilizando o método extend().

A primeira lista é estendida com os elementos da segunda lista, ou seja, a lista2 é acrescentada no final da lista1, resultando em uma lista única contendo todos os elementos de ambas as listas.

No exemplo acima, a saída impressa será:

In [50]:
lista1 = [1, 2, 5, 7]
lista2 = [3, 6]
lista1.extend(lista2)
print('Juntando duas listas:', lista1)

Juntando duas listas: [1, 2, 5, 7, 3, 6]


Esse código abaixo utiliza os métodos count() e index() para operar na lista lista. O método count() conta quantas vezes o número 8 aparece na lista, enquanto o método index() retorna a posição da primeira ocorrência do número 8 na lista. A segunda chamada de index() utiliza um segundo argumento para buscar a primeira ocorrência de 8 a partir da posição 1 da lista.

In [54]:
lista = [1, 2, 78, 64, 3, 1, 1]
print('Removendo o último elemento:', lista.pop())
print('Removendo o elemento de posição 2:' ,lista.pop(2))
print('Removendo a primeira ocorrência do número 1...')
lista.remove(1)
print(lista)

Removendo o último elemento: 1
Removendo o elemento de posição 2: 78
Removendo a primeira ocorrência do número 1...
[2, 64, 3, 1]


O código abaixo cria uma lista com os elementos [1, 2, 3, 5, 9, 12], em seguida utiliza o método sort() para ordenar os elementos em ordem crescente. Então, utiliza o método reverse() para inverter a ordem dos elementos da lista, resultando na lista [12, 9, 5, 3, 2, 1].

In [55]:
lista = [1, 2, 3, 5, 9, 12]
lista.sort()
print('Lista ordenada:', lista)
lista.reverse()
print('Após inverter a lista:', lista)

Lista ordenada: [1, 2, 3, 5, 9, 12]
Após inverter a lista: [12, 9, 5, 3, 2, 1]


O código abaixo cria uma lista chamada lista com os elementos [2, 4, 6, 7, 9, 13, 14]. Em seguida, importa-se o método shuffle do módulo random e aplica esse método à lista lista, o que resulta em uma lista com a ordem aleatória dos elementos. O resultado é impresso na tela através da função print.

In [56]:
lista = [2, 4, 6, 7, 9, 13, 14]
from random import shuffle
shuffle(lista)
print('Embaralhando a lista: ', lista)

Embaralhando a lista:  [4, 6, 13, 2, 14, 9, 7]


O código abaixo define uma lista de strings com três elementos e utiliza o método join() para concatenar os elementos da lista separando-os por um ponto e vírgula (;). O resultado é uma única string contendo todos os elementos da lista separados pelo caractere especificado. No caso do código, a saída será: "Introdução a Python; Banco de Dados; Redes de Computadores".

In [58]:
lista = ['Introdução a Python', 'Banco de Dados', 'Redes de Computadores']
print('Utilizando o join com listas: ', ';'.join(lista))

Utilizando o join com listas:  Introdução a Python;Banco de Dados;Redes de Computadores


O código abaixo recebe uma string 'Exemplo do uso de split em Python' e utiliza o método split() para separar as palavras da frase em uma lista, utilizando o espaço como separador padrão. O resultado é uma lista ['Exemplo', 'do', 'uso', 'de', 'split', 'em', 'Python'] que é impressa junto com o tipo de dado da lista (que deve ser 'list').

In [59]:
frase = 'Exemplo do uso de split em Python'
lista = frase.split()
print(type(lista))
print(lista)

<class 'list'>
['Exemplo', 'do', 'uso', 'de', 'split', 'em', 'Python']


---
### Tupla - tuple

Uma tupla em Python é uma estrutura de dados semelhante a uma lista, mas é imutável, o que significa que não pode ser modificada após a sua criação. Uma tupla é definida entre parênteses e seus elementos são separados por vírgulas.

Por exemplo:

In [63]:
tupla = (1, 2, 3, 4, 5)

Uma tupla pode conter elementos de diferentes tipos, incluindo outras tuplas. Também é possível criar uma tupla vazia usando apenas parênteses, como:

In [65]:
tupla_vazia = ()

Tuplas podem ser acessadas e iteradas de maneira semelhante a listas, usando índices e loops for. Além disso, tuplas podem ser usadas em operações de atribuição múltipla, onde cada elemento da tupla é atribuído a uma variável separada por vírgulas, como:

In [67]:
# Neste exemplo, as variáveis a, b e c recebem, respectivamente, os valores 1, 2 e 3 da tupla tupla.
tupla = (1, 2, 3)
a, b, c = tupla

O código abaixo tenta atribuir o valor 90 ao segundo elemento da tupla. No entanto, como as tuplas são imutáveis em Python, essa operação não é permitida e resultará em um erro de tipo "TypeError: 'tuple' object does not support item assignment". Isso significa que a tentativa de modificar um elemento de uma tupla resultará em um erro, pois as tuplas são projetadas para serem imutáveis e os elementos de uma tupla não podem ser modificados depois de criados. Para modificar uma tupla, é necessário criar uma nova tupla com os valores desejados.

In [68]:
tupla = (1, 2, 78, 64, 3)
tupla[1] = 90

TypeError: 'tuple' object does not support item assignment

O código abaixo define uma tupla tupla com os elementos (1, 2, 78, 64, 3, 98, 736).
A linha print(tupla[0]) imprime o primeiro elemento da tupla, que é 1.
A linha print(tupla[1:4]) imprime um slice da tupla que começa no índice 1 (segundo elemento) e termina no índice 4 (quarto elemento), mas não inclui o elemento no índice 4. Portanto, o resultado é uma nova tupla com os elementos (2, 78, 64).

In [70]:
tupla = (1, 2, 78, 64, 3, 98, 736)
print(tupla[0])
print(tupla[1:4])

1
(2, 78, 64)


O código abaixo primeiro cria uma nova tupla que é formada pelos elementos da tupla original a partir do índice 2 (78, 64, 3), seguidos pelo elemento 50. A tupla original não é modificada, mas sim criada uma nova tupla com os elementos desejados.

O segundo código cria uma nova tupla que é formada pela repetição dos elementos da tupla original entre os índices 1 e 3, três vezes. Portanto, a nova tupla será (2, 78, 64, 2, 78, 64, 2, 78, 64). Assim como no primeiro código, a tupla original não é modificada, mas sim criada uma nova tupla com os elementos desejados.

In [71]:
tupla = (1, 2, 78, 64, 3)
tupla = tupla[2:] + (50,) #uma nova tupla é criada
print(tupla)
tupla = (1, 2, 78, 64, 3)
tupla = tupla[1:3] * 3 #uma nova tupla é criada
print(tupla)

(78, 64, 3, 50)
(2, 78, 2, 78, 2, 78)


O código abaixo apresenta algumas aplicações práticas da tupla em Python.

Na primeira aplicação, é mostrado como é possível realizar uma atribuição simultânea de valores a partir de uma tupla. Nesse caso, é trocado o valor de duas variáveis utilizando a sintaxe a, b = b, a.

Na segunda aplicação, é apresentada uma função que retorna uma tupla com o maior e o menor valor entre dois números. Em seguida, é mostrado como é possível armazenar essa tupla em uma variável e também como é possível atribuir cada valor da tupla a uma variável separada.

In [72]:
# Atribuição de tupla:
a, b = b, a

In [73]:
# Valores de retorno em funçõers:

def maiorMenor(a, b):
    if (a > b):
        return (a, b)
    else:
        return (b, a)

In [74]:
tupla = maiorMenor(5, 8)
print(type(tupla))
maior, menor = maiorMenor(5, 8)
print('Tupla: ', tupla)
print('Maior:',maior, 'Menor:', menor)

<class 'tuple'>
Tupla:  (8, 5)
Maior: 8 Menor: 5


---
## Dicionário - dict

Um dicionário em Python é uma coleção de objetos que consiste em pares chave-valor. A chave é uma string, um número ou outro objeto imutável que é usado como identificador exclusivo para cada valor no dicionário. Já o valor pode ser qualquer objeto, incluindo uma lista, tupla, conjunto, dicionário ou até mesmo uma função.

Na definição do dicionário, cada par chave-valor é separado por vírgula e cada par é separado por dois pontos. Os pares são então colocados entre chaves para formar o dicionário completo.

No exemplo apresentado, o dicionário é definido com as chaves sendo números inteiros e os valores sendo strings representando os nomes de alunos. A função type() é usada para verificar o tipo do objeto (no caso, um dicionário) e a função len() é usada para verificar o número de pares chave-valor no dicionário.

Criando um dicionário vazio e adicionando valores a ele:

In [75]:
# Criando um dicionário vazio
dicionario = {}

# Adicionando valores ao dicionário
dicionario['chave1'] = 'valor1'
dicionario['chave2'] = 'valor2'
dicionario['chave3'] = 'valor3'

print(dicionario)
# Saída: {'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}

{'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}


Criando um dicionário com valores iniciais:

In [76]:
# Criando um dicionário com valores iniciais
dicionario = {'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}

print(dicionario)
# Saída: {'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}

{'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}


Acessando valores do dicionário:

In [78]:
# Acessando valores do dicionário
dicionario = {'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}

print(dicionario['chave2'])
# Saída: 'valor2'

valor2


Modificando valores do dicionário:

In [79]:
# Modificando valores do dicionário
dicionario = {'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}

dicionario['chave2'] = 'novo_valor'

print(dicionario)
# Saída: {'chave1': 'valor1', 'chave2': 'novo_valor', 'chave3': 'valor3'}

{'chave1': 'valor1', 'chave2': 'novo_valor', 'chave3': 'valor3'}


Removendo um par chave-valor do dicionário:

In [81]:
# Removendo um par chave-valor do dicionário
dicionario = {'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}

del dicionario['chave2']

print(dicionario)
# Saída: {'chave1': 'valor1', 'chave3': 'valor3'}

{'chave1': 'valor1', 'chave3': 'valor3'}


Percorrendo um dicionário:

In [82]:
# Percorrendo um dicionário
dicionario = {'chave1': 'valor1', 'chave2': 'valor2', 'chave3': 'valor3'}

for chave, valor in dicionario.items():
    print(chave, valor)

# Saída:
# chave1 valor1
# chave2 valor2
# chave3 valor3

chave1 valor1
chave2 valor2
chave3 valor3


Nesse código abaixo, é criado um dicionário chamado "alunos" com quatro pares de chave-valor, onde cada chave é um número de matrícula e cada valor é o nome de um aluno.

Em seguida, são apresentadas algumas operações com o dicionário. A função "keys()" é utilizada para obter uma lista com as chaves do dicionário, e a função "values()" é utilizada para obter uma lista com os valores do dicionário. Ambas as listas são impressas na tela com as funções "print()".

Por fim, é mostrado um exemplo de como percorrer todos os pares de chave-valor do dicionário utilizando um loop "for". A variável "chave" assume o valor de cada chave do dicionário em cada iteração, e o valor correspondente é acessado utilizando a sintaxe "alunos[chave]". Os valores são impressos na tela utilizando a função "print()".

In [83]:
alunos = {3035: 'Alexandre', 8965: 'Maria', 7674: 'Carlos', 6758: 'José'}
print('Chaves do dicionário: ', alunos.keys())
print('Valores do dicionário: ', alunos.values())
print('Percorrendo o dicionário...')

for chave in alunos:
    print('Chave: ', chave, 'Valor: ', alunos[chave])

Chaves do dicionário:  dict_keys([3035, 8965, 7674, 6758])
Valores do dicionário:  dict_values(['Alexandre', 'Maria', 'Carlos', 'José'])
Percorrendo o dicionário...
Chave:  3035 Valor:  Alexandre
Chave:  8965 Valor:  Maria
Chave:  7674 Valor:  Carlos
Chave:  6758 Valor:  José


O código apresenta algumas aplicações práticas do dicionário em Python.

Na primeira aplicação, é criado um dicionário chamado contatos contendo nomes de pessoas como chaves e seus respectivos números de telefone como valores. Em seguida, é mostrado como acessar um valor específico no dicionário, usando a chave correspondente, através da sintaxe contatos['Maria'].

Na segunda aplicação, é utilizado um loop for para percorrer todas as chaves do dicionário e imprimir seus respectivos valores. Isso é feito usando a sintaxe for chave in contatos: e acessando o valor correspondente a cada chave usando a sintaxe contatos[chave].

Por fim, é utilizado o método get() do dicionário para acessar um valor específico. Caso a chave não exista no dicionário, o método retorna o valor padrão especificado, que é "Contato não encontrado" nesse caso. Essa abordagem evita que um erro seja produzido quando a chave não existe no dicionário.

In [85]:
contatos = {'Alexandre': '998549398', 'Maria': '975748315', 'Carlos': '975634251',
'José': '996453261'}
print(contatos)
print(contatos['Maria'])
for chave in contatos:
    print('Nome:', chave, 'Telefone:', contatos[chave])
    print(contatos.get('Sílvia', 'Contato não encontrado')) #para não produzir erro

{'Alexandre': '998549398', 'Maria': '975748315', 'Carlos': '975634251', 'José': '996453261'}
975748315
Nome: Alexandre Telefone: 998549398
Contato não encontrado
Nome: Maria Telefone: 975748315
Contato não encontrado
Nome: Carlos Telefone: 975634251
Contato não encontrado
Nome: José Telefone: 996453261
Contato não encontrado


Este código apresenta algumas aplicações práticas do dicionário em Python.

Primeiramente, é criado um dicionário chamado "alunos" com quatro elementos, cada um consistindo de uma chave (o RA do aluno) e um valor (o nome do aluno).

Em seguida, é realizado um loop usando o método ".items()" do dicionário para percorrer todas as chaves e valores do dicionário. Dentro do loop, é impresso o RA e o nome de cada aluno.

Depois, é definida uma variável chamada "search" com o valor 'alexandre'. Em seguida, é realizado um segundo loop usando o método ".items()" do dicionário para percorrer todas as chaves e valores do dicionário novamente. Dentro deste loop, é realizada uma verificação para ver se o nome do aluno em questão corresponde à busca realizada na variável "search" (ignorando maiúsculas e minúsculas). Se a busca for encontrada, é impresso o RA e o nome correspondente.

Em resumo, o código mostra como percorrer um dicionário usando loops, como acessar as chaves e valores do dicionário e como realizar buscas dentro do dicionário.

In [86]:
alunos = {3035: 'Alexandre', 8965: 'Maria', 7674: 'Carlos', 6758: 'Lucas'}
for RA, nome in alunos.items():
    print('RA:', RA, 'nome:', nome)
    search = 'alexandre'
print('Procurando Alexandre...')
for RA, nome in alunos.items():
    if (search.lower() == nome.lower()):
        print('RA:', RA, 'nome:', nome)

RA: 3035 nome: Alexandre
RA: 8965 nome: Maria
RA: 7674 nome: Carlos
RA: 6758 nome: Lucas
Procurando Alexandre...
RA: 3035 nome: Alexandre


O código define um dicionário chamado contatos que contém informações de contato de algumas pessoas.

A chave do dicionário é o nome da pessoa e o valor é outro dicionário contendo informações como telefone e endereço. No caso específico de Maria, seu valor é um dicionário com as chaves 'TEL' e 'END'.

O primeiro print exibe o valor da chave 'Maria', que é um dicionário contendo as informações de telefone e endereço. O segundo print exibe apenas o valor da chave 'TEL' dentro do dicionário de Maria, que é o número de telefone '975748315'.

In [87]:
contatos = {
'Alexandre': '998549398',
'Maria': {'TEL': '975748315', 'END': 'Rua x, 100'},
'Carlos': '975634251',
'José': '996453261'
}
print(contatos['Maria'])
print(contatos['Maria']['TEL'])

{'TEL': '975748315', 'END': 'Rua x, 100'}
975748315


Nesse exemplo abaixo, é criada uma lista chamada lista_contatos, que contém quatro tuplas com informações de contatos. Em seguida, essa lista é transformada em um dicionário utilizando a função dict().

A função dict() é utilizada para criar um dicionário a partir de uma sequência de pares chave-valor. No caso desse exemplo, cada tupla da lista contém um nome e um número de telefone, e a função dict() é utilizada para transformar esses pares em um dicionário, onde o nome é a chave e o número de telefone é o valor correspondente.

Ao imprimir o dicionário resultante, é possível ver que a lista foi transformada com sucesso em um dicionário.

In [88]:
lista_contatos = [('Alexandre', '9065868'), ('Pedro', '998679999'),
('Maria', '987654321'), ('Carla', '988777788')]
contatos = dict(lista_contatos)
print('Transformando uma lista em dicionário: ', contatos)

Transformando uma lista em dicionário:  {'Alexandre': '9065868', 'Pedro': '998679999', 'Maria': '987654321', 'Carla': '988777788'}


Esse código abaixo apresenta algumas operações de atualização e inserção de itens em um dicionário em Python.

Na primeira parte do código, o dicionário alunos é criado com quatro itens, sendo a chave o RA do aluno e o valor o nome do aluno. Em seguida, é feita uma atualização no valor correspondente à chave 3035, alterando o nome do aluno de "Alexandre" para "Alexandre Siqueira".

Na segunda parte do código, são feitas operações de inserção de novos alunos no dicionário. Primeiramente, é inserido um novo aluno com a chave 9856 e o valor 'Sílvia'. Em seguida, são inseridos dois novos alunos utilizando o método update, que recebe um dicionário como argumento, contendo as novas chaves e valores a serem inseridos no dicionário. Ao final das inserções, é impresso o dicionário atualizado com todos os alunos.

In [89]:
alunos = {3035: 'Alexandre', 8965: 'Maria', 7674: 'Carlos', 6758: 'José'}
print('Atualizando um aluno...')
alunos[3035] = 'Alexandre Siqueira'
print(alunos)
print('Inserindo alunos...')
alunos[9856] = 'Sílvia'
alunos.update({6895: 'Pedro', 8676: 'Julia'})
print(alunos)

Atualizando um aluno...
{3035: 'Alexandre Siqueira', 8965: 'Maria', 7674: 'Carlos', 6758: 'José'}
Inserindo alunos...
{3035: 'Alexandre Siqueira', 8965: 'Maria', 7674: 'Carlos', 6758: 'José', 9856: 'Sílvia', 6895: 'Pedro', 8676: 'Julia'}


O código abaixo cria um dicionário chamado alunos com quatro pares de chave-valor, onde as chaves são números inteiros que representam o RA (registro acadêmico) dos alunos e os valores são os nomes dos alunos.

Em seguida, o código remove o aluno com RA igual a 3035 usando o comando del alunos[3035]. Depois, o código tenta remover o aluno com RA igual a 1000 usando o comando alunos.pop(1000,'Aluno não encontrado!'), que tenta remover o elemento do dicionário com chave igual a 1000. Se esse elemento não existir, a mensagem 'Aluno não encontrado!' é retornada. No entanto, como não há nenhum elemento com chave igual a 1000 no dicionário, a mensagem é impressa na tela. Note que a variável alunos não é modificada pela chamada a pop() neste caso.

In [90]:
alunos = {3035: 'Alexandre', 8965: 'Maria', 7674: 'Carlos', 6758: 'Lucas'}
print('Removendo o aluno 3035...')
del alunos[3035]
alunos
print('Tentando remover o aluno 1000...')
print(alunos.pop(1000,'Aluno não encontrado!'))

Removendo o aluno 3035...
Tentando remover o aluno 1000...
Aluno não encontrado!


O código abaixo apresenta um exemplo de aplicação da biblioteca json em conjunto com a biblioteca requests. A função requests.get() é utilizada para realizar uma requisição HTTP na URL especificada e obter os dados no formato JSON contidos na resposta da requisição. A função json.loads() é utilizada para converter o conteúdo JSON em um objeto Python.

No exemplo apresentado, a URL utilizada contém dados sobre filmes em formato JSON. A variável filmes recebe o conteúdo JSON convertido para um objeto Python. Em seguida, é feito um loop pela lista de filmes e cada filme é impresso na tela. Depois, o primeiro filme é armazenado na variável filme, que é do tipo dict. A função type() é utilizada para mostrar o tipo do objeto filme.

In [ ]:
import json
import requests
response = requests.get("https://raw.githubusercontent.com/prust/wikipedia-movie-data/master/movies.json")
filmes = json.loads(response.text)
for filme in filmes:
    print(filme)
    filme = filmes[0]
print(filme)
print(type(filme))

---
### Conjunto - set


Um conjunto (set) é uma coleção de itens desordenada que não pode conter elementos duplicados. É parcialmente imutável, o que significa que você pode adicionar ou remover elementos, mas não pode alterar um item específico.

Conjuntos são geralmente usados com operações matemáticas de união, interseção e diferença simétrica. Por exemplo, você pode usar conjuntos para remover duplicatas de uma lista ou verificar quais elementos duas listas têm em comum.

Na sintaxe Python, um conjunto pode ser definido usando chaves {} ou usando a função set(). No exemplo apresentado, conjunto_1 e conjunto_2 são conjuntos equivalentes, mas definidos de maneiras diferentes. A função type() é usada para verificar o tipo de dados do conjunto, que é "set" neste caso.

Exemplo:

In [93]:
conjunto_1 = {10, 20, 30, 40, 40}
conjunto_2 = set([10,20,30,40,40])
print(conjunto_1)  # {40, 10, 20, 30}
print(conjunto_2)  # {40, 10, 20, 30}

{40, 10, 20, 30}
{40, 10, 20, 30}


Nesse exemplo, dois conjuntos são criados. Note que mesmo o número 40 aparecendo duas vezes, ele só é adicionado uma vez em cada conjunto. Isso ocorre porque conjuntos não permitem elementos duplicados.

In [95]:
# Nesse exemplo, dois conjuntos são criados e é realizada a união, interseção e diferença simétrica entre eles. Note que os resultados das operações são conjuntos que contêm elementos únicos e desordenados.
conjunto_a = {1, 2, 3, 4}
conjunto_b = {3, 4, 5, 6}
print(conjunto_a.union(conjunto_b))  # {1, 2, 3, 4, 5, 6}
print(conjunto_a.intersection(conjunto_b))  # {3, 4}
print(conjunto_a.symmetric_difference(conjunto_b))  # {1, 2, 5, 6}

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2, 5, 6}


Criação de um conjunto:

O conjunto é criado utilizando chaves {} ou a função set(). Os elementos do conjunto são separados por vírgulas. O conjunto não pode conter elementos duplicados.

Exemplo:

In [96]:
conjunto = {10, 20, 30, 10, 20, 20, 10, 40}

Adicionando um elemento ao conjunto

O método add() é utilizado para adicionar um único elemento ao conjunto. Se o elemento já estiver presente no conjunto, o método não adicionará novamente.

Exemplo:

In [97]:
conjunto.add(2)
print("Adicionando um elemento...", conjunto)

Adicionando um elemento... {2, 40, 10, 20, 30}


--

Adicionando vários elementos ao conjunto

O método update() é utilizado para adicionar vários elementos ao conjunto. Os elementos são passados como uma lista ou outro conjunto. O método remove os elementos duplicados.

Exemplo:

In [98]:
conjunto.update([40, 50, 60])
print("Adicionando vários elementos...", conjunto)

Adicionando vários elementos... {2, 40, 10, 50, 20, 60, 30}


Removendo um elemento do conjunto

O método discard() é utilizado para remover um elemento específico do conjunto. Se o elemento não estiver presente, o método não fará nada.

Exemplo:

In [99]:
conjunto.discard(2)
print("Removendo um elemento...", conjunto)

Removendo um elemento... {40, 10, 50, 20, 60, 30}


Esse código mostra exemplos de operações com conjuntos em Python.

Criação de conjuntos:

In [100]:
conjunto_1 = {10, 15, 20, 30}
conjunto_2 = set([5, 10, 15, 30, 40])

O primeiro conjunto é criado utilizando a sintaxe de chaves com os elementos separados por vírgula, enquanto o segundo é criado utilizando a função set() e uma lista de elementos como argumento.

União de conjuntos:

In [101]:
print("União...")
print(conjunto_1 | conjunto_2) # {5, 40, 10, 15, 20, 30}
print(conjunto_1.union(conjunto_2)) # {5, 40, 10, 15, 20, 30}

União...
{5, 40, 10, 15, 20, 30}
{5, 40, 10, 15, 20, 30}


A união de conjuntos é realizada utilizando o operador | ou o método union(). O resultado é um conjunto contendo todos os elementos dos dois conjuntos, sem repeti-los.

Interseção de conjuntos:

In [103]:
# A interseção de conjuntos é realizada utilizando o operador & ou o método intersection(). 
# O resultado é um conjunto contendo apenas os elementos que estão presentes em ambos os conjuntos.
print("Interseção...")
print(conjunto_1 & conjunto_2) # {10, 30, 15}
print(conjunto_1.intersection(conjunto_2)) # {10, 30, 15}

Interseção...
{10, 30, 15}
{10, 30, 15}


--

Podemos explicar o código abaixo da seguinte maneira:

Criando conjuntos:

In [104]:
conjunto_1 = {10, 15, 20, 30}
conjunto_2 = set([5, 10, 15, 30, 40])

Neste trecho de código, dois conjuntos são criados: conjunto_1 com os elementos {10, 15, 20, 30} e conjunto_2 com os elementos {5, 10, 15, 30, 40}.

Diferença:

In [105]:
print("Diferença")
print(conjunto_1 - conjunto_2) # {20}
print(conjunto_1.difference(conjunto_2)) # {20}

Diferença
{20}
{20}


Neste trecho de código, a diferença entre os conjuntos é calculada e os resultados são impressos na tela. A diferença entre conjunto_1 e conjunto_2 são os elementos que pertencem apenas a conjunto_1 e não a conjunto_2. Portanto, o resultado é o conjunto {20}.

Diferença Simétrica:

In [107]:
# Neste trecho de código, a diferença simétrica entre os conjuntos é calculada e os resultados são impressos na tela. 
# A diferença simétrica entre conjunto_1 e conjunto_2 são os elementos que pertencem a apenas um dos conjuntos. 
# Portanto, o resultado é o conjunto {20, 5, 40}.
print("Diferença Simétrica")
print(conjunto_1 ^ conjunto_2) # {20, 5, 40}
print(conjunto_1.symmetric_difference(conjunto_2)) # {20, 5, 40}

Diferença Simétrica
{20, 5, 40}
{20, 5, 40}
